bracketSpacing = false
plugins = ['prettier-plugin-organize-attributes']
semi = false
singleQuote = true
jsxSingleQuote = true

[[overrides]]
files = ['*.dj.html', '*.j2.html']
[overrides.options]
parser = 'jinja-template'
plugins = ['prettier-plugin-jinja-template']

[[overrides]]
files = ['*.toml']
[overrides.options]
plugins = ['prettier-plugin-toml']
