- id: actionlint
  entry: actionlint
  files: ^.github/workflows/
  language: system
  name: actionlint

- id: cookiecutter
  # Allow overwriting with . to test local changes
  args:
      - https://github.com/biobuddies/helicopyter.git
  entry: cookiecutter --config-file .cookiecutter.yaml --no-input --overwrite-if-exists
  language: system
  name: cookiecutter
  pass_filenames: false
  stages:
      - manual # because Internet

- id: django-upgrade
  entry: django-upgrade
  language: system
  name: django-upgrade
  types:
      - python

- id: djlint-django
  entry: djlint --profile=django --reformat
  language: system
  name: djlint-django
  types:
      - html

- id: djlint-jinja
  entry: djlint --profile=jinja --reformat
  language: system
  name: djlint-jinja
  types:
      - jinja

# Replace with typos
- id: dot-yaml
  description: Require four letter suffix http://www.yaml.org/faq.html
  entry: dot-yaml
  files: .*\.yml$ # noqa:typos
  language: fail
  name: dot-yaml

- id: end-of-file-fixer
  entry: end-of-file-fixer
  language: system
  name: end-of-file-fixer
  types:
      - text

- id: hadolint
  entry: hadolint
  language: system
  name: hadolint
  types:
      - dockerfile

- id: helicopyter
  entry: bash .biobuddies/includes.bash hs
  files: ^(helicopyter\.py|deploys/.+/terraform/main\.py)$
  language: system
  name: helicopyter
  # Without this, there can be a useless run with specific deploys/*/terraform/main.py files,
  # followed by the run for all deploys/*/terraform/main.py files (triggered by helicopyter.py)
  require_serial: true

- id: mailmap
  entry: bash .biobuddies/includes.bash check_mailmap
  language: system
  name: mailmap
  pass_filenames: false

- id: mypy
  entry: mypy .
  language: system
  name: mypy
  pass_filenames: false
  stages:
      - manual # Because slow
  types:
      - python

# Relies on .prettierrc.toml from cookiecutter
- id: prettier-write
  entry: node_modules/.bin/prettier --write
  exclude: ^deploys/.+/terraform/main.tf.json$
  language: system
  name: prettier-write
  types_or:
      - json
      - yaml
      - toml
      - ts

# Relies on .biobuddies/ruff.toml from cookiecutter
- id: ruff-check-fix
  args:
      - --fix
  entry: ruff check --force-exclude
  language: system
  name: ruff
  require_serial: true
  types_or:
      - python
      - pyi

# Relies on .biobuddies/ruff.toml from cookiecutter
- id: ruff-format
  entry: ruff format --force-exclude
  language: system
  name: ruff-format
  require_serial: true
  types_or:
      - python
      - pyi

# Relies on .shellcheckrc from cookiecutter
- id: shellcheck
  entry: shellcheck
  language: system
  name: shellcheck
  require_serial: true # shellcheck can detect sourcing this way
  types:
      - shell

- id: shfmt
  entry: |
      shfmt --binary-next-line --case-indent --simplify --write --indent 4 --language-dialect bash
  language: system
  name: shfmt
  types:
      - shell

- id: trailing-whitespace-fixer
  entry: trailing-whitespace-fixer
  exclude: ^\.github/pull_request_template\.md$
  language: system
  name: trailing-whitespace-fixer
  types:
      - text

- id: typos
  args:
      - --config
      - .biobuddies/typos.toml
  entry: typos --write-changes
  # First, files that contain misspellings
  # Then, files copied by cookiecutter
  exclude: |
      (?x)^(
          |documentation/self2024-python-defined-infrastructure\.md
          |\.biobuddies/.+
          |\.github/pull_request_template.md
          |\.editorconfig
          |\.prettierrc.toml
          |\.shellcheckrc
          |\.yamllint.yaml
      )$
  types:
      - text
  language: system
  name: typos

- id: validate-pyproject
  entry: validate-pyproject
  files: ^pyproject.toml$
  language: system
  name: Validate pyproject.toml

- id: uv-pip-check
  entry: uv pip check
  language: system
  name: uv-pip-check
  pass_filenames: false

- id: uv-pip-compile
  entry: bash .biobuddies/includes.bash upc
  language: system
  name: uv-pip-compile

# Relies on .yamllint.yaml from cookiecutter
- id: yamllint
  entry: yamllint
  language: system
  name: yamllint
  types:
      - yaml
