- id: dot-yaml
  description: Require four letter suffix http://www.yaml.org/faq.html
  entry: dot-yaml
  files: .*\.yml$
  language: fail
  name: dot-yaml

- id: gitignore-node-python-terraform
  entry: >
      bash -c 'langs={Node,Python,Terraform};
      curl -s https://raw.githubusercontent.com/github/gitignore/main/$langs.gitignore >
      .gitignore'
  language: system
  name: gitignore-node-python-terraform
  pass_filenames: false

- id: helicopyter-all
  entry: python -m helicopyter all
  files: helicopyter.py
  language: system
  name: helicopyter-all
  pass_filenames: false

- id: helicopyter-codenames
  entry: python -m helicopyter
  files: deploys/.+/terraform/main.py
  language: system
  name: helicopyter-codenames

- id: mypy
  entry: mypy .
  language: system
  name: mypy
  pass_filenames: false
  types:
      - python
  stages:
      - manual

# uv-pip-check recommended instead
- id: pip-check
  entry: pip check
  language: system
  name: pip-check
  pass_filenames: false

- id: prettier-write
  entry: node_modules/.bin/prettier --write
  language: system
  name: prettier-write
  types_or:
      - json
      - yaml
      - toml
      - ts

- id: ruff-check-fix
  args:
      - --fix
  entry: ruff check --force-exclude
  language: system
  name: ruff
  require_serial: true
  types_or:
      - python
      - pyi

- id: ruff-format
  entry: ruff format --force-exclude
  language: system
  name: ruff-format
  require_serial: true
  types_or:
      - python
      - pyi

- id: shellcheck
  name: shellcheck
  entry: shellcheck
  language: system
  types:
      - shell
  require_serial: true # shellcheck can detect sourcing this way

- id: validate-pyproject
  entry: validate-pyproject
  files: ^pyproject.toml$
  name: Validate pyproject.toml
  language: system

- id: uv-pip-check
  entry: uv pip check
  language: system
  name: uv-pip-check

- id: uv-pip-compile
  entry: uv pip compile -o requirements.txt --python-platform linux
  files: requirements.in
  language: system
  name: uv-pip-compile

- id: yamllint
  entry: yamllint
  language: system
  name: yamllint
  types:
      - file
      - yaml
