extends: default

rules:
    comments:
        min-spaces-from-content: 1 # Unfortunate difference between prettier and black
    document-start: disable
    indentation:
        spaces: 4
    line-length:
        max: 120
    truthy:
        level: error
