[build-system]
backend-path = ['']
build-backend = 'pypi_compatible_build'
requires = ['setuptools>=77', 'setuptools_scm']

[project]
classifiers = [
    
    'Operating System :: OS Independent',
    
    'Programming Language :: Python :: 3.12',
    
    'Topic :: System :: Installation/Setup',
    
    'Topic :: System :: Systems Administration',
    
]
description = 'Python-defined infrastructure'
license = 'MPL-2.0'
name = 'helicopyter'
readme = 'README.md'
requires-python = '>=3.12'
dynamic = ['version']

dependencies = [
    
    'typed-argument-parser',
    
]

[project.optional-dependencies]
build = [
    'setuptools',
]
cdktf = [
    'cdktf',
]
demos = [
    'cdktf-cdktf-provider-aws',
    'cdktf-cdktf-provider-cloudflare==11.*',
    'cdktf-cdktf-provider-docker',
    'cdktf-cdktf-provider-github',
    'cdktf-cdktf-provider-null',
]
pre-commit = [
    'actionlint-py',
    'basedpyright',
    'cookiecutter',
    'django-upgrade',
    'djlint>=1.45.0',
    'hadolint-py @ git+https://github.com/AleksaC/hadolint-py.git',
    'pre-commit-hooks',
    'pyrefly',
    'ruff',
    'shellcheck-py',
    'shfmt-py',
    'styleforce',
    'typos',
    'validate-pyproject[all]',
    'yamllint',
]
test = [
    'pytest',
    'pytest-cov',
    'rust-just',
]

[project.urls]
source = 'https://github.com/biobuddies/helicopyter'

[tool.coverage.run]
source_pkgs = ['helicopyter']

[tool.pytest.ini_options]
norecursedirs = ['.venv', 'node_modules', '{{cookiecutter.dot}}']

[tool.setuptools]
py-modules = ['helicopyter']

# TODO measles renders py-modules only; teach it packages, then stop overriding after cookiecutter
[tool.setuptools.packages.find]
exclude = ['deploys*', 'node_modules*'] # Applies to wheel but not sdist

[tool.setuptools_scm]

[tool.basedpyright]
extends = '.biobuddies/basedpyright.toml'

[tool.djlint]
close_void_tags = true
format_attribute_template_tags = true
indent = 4
max_attribute_length = 100
max_blank_lines = 1
max_line_length = 100
quote_style = 'single'

[tool.ruff]
extend = '.biobuddies/ruff.toml'

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
