"""Exercise the CLI without CDKTF or Node.js."""

from os import environ, pathsep
from pathlib import Path
from subprocess import check_output
from sys import executable
from textwrap import dedent

from pytest import mark


@mark.parametrize('arguments', (['--help'], ['example'], ['example', '--format_with', 'cat']))
def test_without_cdktf(tmp_path: Path, arguments: list[str]) -> None:
    (tmp_path / 'sitecustomize.py').write_text(
        "import sys\nsys.modules.update(dict.fromkeys(('cdktf', 'constructs', 'jsii')))\n"
        'from pathlib import Path\n'
        'import helicopyter\n'
        'def format_hcl(command, *, input, stderr):\n'
        "    Path('formatter.txt').write_text(' '.join(command))\n"
        '    return input\n'
        'helicopyter.check_output = format_hcl\n'
    )
    deploy = tmp_path / 'deploys' / 'example' / 'terraform'
    deploy.mkdir(parents=True)
    (tmp_path / 'deploys' / '__init__.py').touch()
    (deploy / 'main.py').write_text(
        "from helicopyter import resource\nresource.terraform_data.example(input='hello')\n"
    )
    output = check_output(
        [executable, '-m', 'helicopyter', *arguments],
        cwd=tmp_path,
        env={
            **environ,
            'PATH': '/usr/bin:/bin',
            'PYTHONPATH': f'{tmp_path}{pathsep}{Path(__file__).parent}',
        },
        text=True,
    )
    if arguments == ['--help']:
        assert 'usage:' in output
    else:
        assert (tmp_path / 'formatter.txt').read_text() == (
            'tofu fmt -' if arguments == ['example'] else 'cat'
        )
        assert 'Generating deploys/example/terraform/main.tf' in output
        assert (deploy / 'main.tf').read_text().strip() == dedent("""
            # AUTOGENERATED by helicopyter

            resource "terraform_data" "example" {
              input = "hello"
            }
        """).strip()
