# AUTOGENERATED by helicopyter

terraform {
  backend "s3" {
    bucket                      = "terraform"
    key                         = "demojamstaff.tfstate"
    region                      = "auto"
    workspace_key_prefix        = "demojamstaff"
    skip_credentials_validation = "true"
    skip_metadata_api_check     = "true"
    skip_region_validation      = "true"
    skip_requesting_account_id  = "true"
    skip_s3_checksum            = "true"
    use_path_style              = "true"
  }
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "5.25.0"
    }
  }
}

provider "cloudflare" {}

data "cloudflare_dns_records" "this" {
  lifecycle {
    postcondition {
      condition     = anytrue([for record in self.result : contains(terraform.workspace == "main" ? ["admin.example.net", "*.example.net"] : ["*.example.net"], record.name)])
      error_message = "Proxied DNS record for admin.example.net or its previews not found"
    }
  }
  name = {
    endswith = "example.net"
  }
  proxied = true
  zone_id = "0123456789abcdef0123456789abcdef01"
}

data "cloudflare_zero_trust_access_application" "this" {
  account_id = "0123456789abcdef0123456789abcdef00"
  filter = {
    domain = "*.example.net"
    exact  = true
  }
  lifecycle {
    postcondition {
      condition     = try(anytrue([for policy in self.policies : policy.decision == "allow"]), false)
      error_message = "Access application *.example.net needs an allow policy"
    }
  }
}

data "cloudflare_zero_trust_tunnel_cloudflared" "this" {
  account_id = "0123456789abcdef0123456789abcdef00"
  filter = {
    is_deleted = false
    name       = "example.net"
  }
  lifecycle {
    postcondition {
      condition     = self.id != null
      error_message = "Tunnel example.net not found"
    }
  }
}

resource "cloudflare_workers_script" "this" {
  account_id = "0123456789abcdef0123456789abcdef00"
  assets = {
    config = {
      not_found_handling = "single-page-application"
      run_worker_first   = ["/api/*"]
    }
    directory = "../../../site"
  }
  bindings = [{
    name = "ALLOWEDFLARE_AUDIENCE"
    text = data.cloudflare_zero_trust_access_application.this.aud
    type = "plain_text"
  }]
  compatibility_date = "2026-08-28"
  content            = "export default {\n    async fetch() {\n        return new Response('API placeholder')\n    },\n}\n"
  main_module        = "worker.js"
  script_name        = "demojamstaff-${terraform.workspace}"
}

resource "cloudflare_workers_script_subdomain" "this" {
  account_id       = "0123456789abcdef0123456789abcdef00"
  enabled          = false
  previews_enabled = false
  script_name      = cloudflare_workers_script.this.script_name
}

resource "cloudflare_workers_route" "this" {
  pattern = terraform.workspace == "main" ? "admin.example.net/*" : "admin-${terraform.workspace}.example.net/*"
  script  = cloudflare_workers_script.this.script_name
  zone_id = "0123456789abcdef0123456789abcdef01"
}
