set export := true
set shell := ['bash', '-euo', 'pipefail', '-c']

# Pre-installed on Sonoma:
#   * Skip upgrades: host, file, less, ps
#   * Upgrade: bash, curl, git (may come with xcode)

BRWS := 'asdf bash curl fping git gnu-sed tmux tree'
DEBS := 'bash bind9-host curl file fping git less procps tmux tree'
JUST := just_executable()
OPSY := `uname -s`

# List all recipes
default:
    {{ JUST }} --list

# print PATH and VERsion; optionally assert version file matches
pathver command version_file="":
    #!/usr/bin/env bash
    # TODO investigate require() instead
    source=$(type -p "{{ command }}")
    if [[ -z $source ]]; then
        source=$(type "{{ command }}")
    fi
    actual=$( "{{ command }}" --version 2>&1 | gsed -En 's/(.+ )?(v?[0-9]+\.[0-9]+\.[^ ]+).*/\2/p')
    echo "$source $actual"
    if [[ -f "{{ version_file }}" ]]; then
        expected=$(cat "{{ version_file }}")
        if [[ $actual != "$expected" && ${actual%.*} != "$expected" ]]; then
            echo "ERROR: $source version $actual does not match {{ version_file }} $expected"
            exit 1
        fi
    fi

# Docker Compose Django Manage
dcdm *args:
    docker compose exec `mise cona` python -m manage {{ args }}

# Docker Compose Push
dcp *args:
    docker compose push --quiet {{ args }}

# Docker Compose Run, respecting docker-compose.yaml port definitions
dcr *args:
    docker compose run --quiet-pull --service-ports {{ args }}

# Docker Compose Shell
dcs *args:
    docker compose run `mise cona` bash {{ args }}

# Docker Compose Up
dcu *args:
    docker compose up {{ args }}

# DEVelopment READYness check
devready:
    bash .biobuddies/includes.bash devready

# FORCE system to be READY for development, clobbering current settings
forceready:
    bash .biobuddies/includes.bash forceready

# Pre-Commit Run (defaults to modified files)
pcr *args:
    {{ if `mise cona` == 'helicopyter' { '.venv/bin/python -m try_repo' } else { 'pre-commit run' } }} {{ args }}

# run Pre-Commit on All files
pca *args:
    @# Seemingly contradicting the help text, experimentation shows hook positional arguments must
    @# come before flags
    {{ JUST }} pcr {{ args }} --all-files

# run Pre-Commit on All files including Manual stage hooks
pcam *args:
    {{ JUST }} pca {{ args }} --hook-stage manual

# run Pre-Commit on modified files including Manual stage hooks
pcm *args:
    {{ JUST }} pcr {{ args }} --hook-stage manual

# git PUSH over https
push *args:
    git push https://${GITHUB_TOKEN}@github.com/{{ `mise orgn` }}/{{ `mise cona` }} {{ args }}

# Update asdf .tool-versions
update:
    echo "uv `asdf latest uv`" > .tool-versions

# Uv venv and Pip Sync
ups *args:
    uv venv --clear --no-progress && uv pip sync --no-progress {{ args }} requirements.txt

# Universally Unique IDentifier
uuid:
    @echo {{ uuid() }}
