[default]
locale = 'en-us'

[default.extend-identifiers]
'iTerm2' = 'iTerm2'
'IDentifier' = 'IDentifier' # Capitalization explaining UUID

[default.extend-words]
# 0xb5 micro sign to 0x3bc Greek small mu
'µL' = 'μL'
'µM' = 'μM'