"""AUTOGENERATED by helicopyter.stubgen; regenerate with `mise helicopyter-stubs`."""

from collections.abc import Iterable
from pathlib import Path
from typing import Any, Protocol, Required, TypedDict, Unpack

from cdktf import TerraformElement, TerraformStack
from tap import Tap

class Block:
    kind: str
    labels: tuple[str, ...]
    attributes: dict[str, Any]
    def __init__(self, kind: str, *labels: str) -> None: ...
    def __call__(self, *labels: str, **kwargs: Any) -> Block: ...
    def __getattr__(self, name: str) -> Block: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def to_hcl(self, depth: int = 0) -> str: ...

# dup helicopyter/__init__.py public interface
registry: list[Block]
cona: str
tbool: Block
number: Block
string: Block
terraform: Block
tlocals: Block
variable: Block
local: Block
var: Block

def quote(value: Any, depth: int = 1) -> str: ...
def autoformat(unformatted: str, format_with: str) -> str: ...
def multisynth(
    all_or_conas_or_paths: Iterable[str],
    *,
    change_directory: Path | None,
    hashicorp_configuration_language: bool,
    format_with: str,
) -> None: ...

class HeliStack(TerraformStack):
    cona: str
    def __init__(self, cona: str) -> None: ...
    def override(self, **kwargs: Any) -> None: ...
    def provide(self, name: str, **kwargs: Any) -> type[TerraformElement]: ...
    def push[E: TerraformElement](
        self, Element: type[E], id_: str, *args: Any, **kwargs: Any
    ) -> E: ...

class Parameters(Tap):
    conas: list[str]
    directory: Path | None
    format_with: str
    hashicorp_configuration_language: bool
    def configure(self) -> None: ...

class Builder[Call]:
    """Type both call styles: resource.kind('name')(...) and resource.kind.name(...)."""

    def __call__(self, *labels: str) -> Call: ...
    def __getattr__(self, name: str) -> Call: ...

class NullProviderArgs(TypedDict, total=False):
    ...

class NullProviderCall(Protocol):
    def __call__(self, **attributes: Unpack[NullProviderArgs]) -> Block: ...
    def __getattr__(self, name: str) -> Block: ...

class NullResourceArgs(TypedDict, total=False):
    triggers: dict[str, str | Block] | str | Block

class NullResourceCall(Protocol):
    def __call__(self, **attributes: Unpack[NullResourceArgs]) -> Block: ...
    def __getattr__(self, name: str) -> Block: ...

class DataNullDataSourceArgs(TypedDict, total=False):
    has_computed_default: str | Block
    inputs: dict[str, str | Block] | str | Block

class DataNullDataSourceCall(Protocol):
    def __call__(self, **attributes: Unpack[DataNullDataSourceArgs]) -> Block: ...
    def __getattr__(self, name: str) -> Block: ...

class DataSources(Block):
    null_data_source: Builder[DataNullDataSourceCall]

data: DataSources

class Providers(Block):
    null: NullProviderCall

provider: Providers

class Resources(Block):
    null_resource: Builder[NullResourceCall]

resource: Resources
