"""
Generate helicopyter/__init__.pyi from `terraform providers schema -json`.

Deploy code keeps calling the small Block runtime; the stub adds erased-at-runtime types so IDE
autocomplete and basedpyright catch attribute typos offline, with `tofu validate` as the semantic
backstop. Run after `mise tinit` so types match .terraform.lock.hcl, and commit the stub like a
lock file.
"""

from json import loads
from keyword import iskeyword
from pathlib import Path
from subprocess import check_output
from typing import Any

from tap import Tap

HEADER = '''"""AUTOGENERATED by helicopyter.stubgen; regenerate with `mise helicopyter-stubs`."""

from collections.abc import Iterable
from pathlib import Path
from typing import Any, Protocol, Required, TypedDict, Unpack

from cdktf import TerraformElement, TerraformStack
from tap import Tap

class Block:
    kind: str
    labels: tuple[str, ...]
    attributes: dict[str, Any]
    def __init__(self, kind: str, *labels: str) -> None: ...
    def __call__(self, *labels: str, **kwargs: Any) -> Block: ...
    def __getattr__(self, name: str) -> Block: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def to_hcl(self, depth: int = 0) -> str: ...

# dup helicopyter/__init__.py public interface
registry: list[Block]
cona: str
tbool: Block
number: Block
string: Block
terraform: Block
tlocals: Block
variable: Block
local: Block
var: Block

def quote(value: Any, depth: int = 1) -> str: ...
def autoformat(unformatted: str, format_with: str) -> str: ...
def multisynth(
    all_or_conas_or_paths: Iterable[str],
    *,
    change_directory: Path | None,
    hashicorp_configuration_language: bool,
    format_with: str,
) -> None: ...

class HeliStack(TerraformStack):
    cona: str
    def __init__(self, cona: str) -> None: ...
    def override(self, **kwargs: Any) -> None: ...
    def provide(self, name: str, **kwargs: Any) -> type[TerraformElement]: ...
    def push[E: TerraformElement](
        self, Element: type[E], id_: str, *args: Any, **kwargs: Any
    ) -> E: ...

class Parameters(Tap):
    conas: list[str]
    directory: Path | None
    format_with: str
    hashicorp_configuration_language: bool
    def configure(self) -> None: ...

class Builder[Call]:
    """Type both call styles: resource.kind('name')(...) and resource.kind.name(...)."""

    def __call__(self, *labels: str) -> Call: ...
    def __getattr__(self, name: str) -> Call: ...
'''


def classify(kind: str) -> str:
    """Rename github_repository style to GithubRepository style."""
    return ''.join(part.capitalize() for part in kind.split('_'))


def annotate(cty: Any) -> str:
    """Map a cty type to a Python annotation; interpolation strings and references always fit."""
    scalars = {'string': 'str', 'bool': 'bool | str', 'number': 'float | str'}
    match cty:
        case str() if cty in scalars:
            return f'{scalars[cty]} | Block'
        case ['list' | 'set', element]:
            return f'list[{annotate(element)}] | str | Block'
        case ['map', element]:
            return f'dict[str, {annotate(element)}] | str | Block'
        case ['object', dict()]:
            return 'dict[str, Any]'
        case _:
            return 'Any'


def usable(key: str) -> bool:
    """Only valid non-keyword identifiers can be passed as keyword arguments."""
    return key.isidentifier() and not iskeyword(key)


def declare(name: str, schema: dict[str, Any]) -> str:
    """Emit an Args TypedDict and Call Protocol pair for one block schema."""
    block = schema.get('block', {})
    lines = [f'class {name}Args(TypedDict, total=False):']
    for key, attribute in sorted(block.get('attributes', {}).items()):
        computed_only = attribute.get('computed') and not attribute.get('optional')
        if not usable(key) or computed_only:
            continue
        annotation = annotate(attribute.get('type'))
        wrapped = f'Required[{annotation}]' if attribute.get('required') else annotation
        lines.append(f'    {key}: {wrapped}')
    lines.extend(
        f'    {key}: Block | dict[str, Any] | list[Any]'
        for key in sorted(block.get('block_types', {}))
        if usable(key)
    )
    if len(lines) == 1:
        lines.append('    ...')
    lines.append(f'\nclass {name}Call(Protocol):')
    lines.append(f'    def __call__(self, **attributes: Unpack[{name}Args]) -> Block: ...')
    # References chain past the label: resource.null_resource.this.id
    lines.append('    def __getattr__(self, name: str) -> Block: ...')
    return '\n'.join(lines)


def generate(provider_schemas: dict[str, Any]) -> str:
    """Render the stub from merged `providers schema -json` provider_schemas."""
    declarations: list[str] = []
    singletons: dict[str, dict[str, str]] = {'data': {}, 'provider': {}, 'resource': {}}
    for address in sorted(provider_schemas):
        schemas = provider_schemas[address]
        short_name = address.rsplit('/', 1)[-1].replace('-', '_')
        if usable(short_name):
            provider_class = f'{classify(short_name)}Provider'
            declarations.append(declare(provider_class, schemas.get('provider', {})))
            singletons['provider'][short_name] = f'{provider_class}Call'
        for kind, schema in sorted(schemas.get('resource_schemas', {}).items()):
            if usable(kind):
                declarations.append(declare(classify(kind), schema))
                singletons['resource'][kind] = f'Builder[{classify(kind)}Call]'
        for kind, schema in sorted(schemas.get('data_source_schemas', {}).items()):
            if usable(kind):
                declarations.append(declare(f'Data{classify(kind)}', schema))
                singletons['data'][kind] = f'Builder[Data{classify(kind)}Call]'
    for singleton, class_name in {
        'data': 'DataSources',
        'provider': 'Providers',
        'resource': 'Resources',
    }.items():
        entries = [f'    {kind}: {call}' for kind, call in singletons[singleton].items()]
        body = entries or ['    ...']
        declarations.append('\n'.join([f'class {class_name}(Block):', *body]))
        declarations.append(f'{singleton}: {class_name}')
    return HEADER + '\n' + '\n\n'.join(declarations) + '\n'


class StubgenParameters(Tap):
    conas: list[str]  # pyright:ignore[reportUninitializedInstanceVariable]
    format_with: str = 'terraform'

    def configure(self) -> None:  # noqa: D102
        self.add_argument('conas', help='space-separated COdeNAmes, or all')


# ruff: noqa: T201
def main() -> None:
    """Merge provider schemas across initialized deploys and write the stub."""
    parameters = StubgenParameters().parse_args()
    conas = (
        sorted(
            lock.parent.parent.name
            for lock in Path('deploys').glob('*/terraform/.terraform.lock.hcl')
        )
        if 'all' in parameters.conas
        else sorted(set(parameters.conas))
    )
    provider_schemas: dict[str, Any] = {}
    for cona in conas:
        print(f'Reading provider schemas from deploys/{cona}/terraform')
        chdir = f'-chdir=deploys/{cona}/terraform'
        output = check_output(  # noqa: S603
            [parameters.format_with, chdir, 'providers', 'schema', '-json']
        )
        provider_schemas.update(loads(output).get('provider_schemas', {}))
    stub = Path(__file__).with_name('__init__.pyi')
    print(f'Generating {stub}')
    stub.write_text(generate(provider_schemas))


if __name__ == '__main__':
    main()
