# AUTOGENERATED by helicopyter

locals {
  cona = "demo"
  envi = terraform.workspace
}

resource "null_resource" "this" {
  provisioner "local-exec" {
    command = "echo $envi"
    environment = {
      envi = "${local.envi}"
    }
  }
}

variable "giha" {
  type = string
}

output "giha" {
  value = var.giha
}
