# AUTOGENERATED by helicopyter

locals {
  cona = "demo"
}

locals {
  envi = terraform.workspace
}

resource "null_resource" "this" {
  provisioner "local-exec" {
    command = "echo $envi"
    environment = {
      envi = "${local.envi}"
    }
  }
}

variable "gash" {
  type = string
}

output "gash" {
  value = var.gash
}
