# AUTOGENERATED by helicopyter

terraform {
  backend "s3" {
    bucket                      = "terraform"
    key                         = "demojampublic.tfstate"
    region                      = "auto"
    workspace_key_prefix        = "demojampublic"
    skip_credentials_validation = "true"
    skip_metadata_api_check     = "true"
    skip_region_validation      = "true"
    skip_requesting_account_id  = "true"
    skip_s3_checksum            = "true"
    use_path_style              = "true"
  }
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "5.25.0"
    }
  }
}

provider "cloudflare" {}

data "cloudflare_dns_records" "this" {
  lifecycle {
    postcondition {
      condition     = anytrue([for record in self.result : contains(terraform.workspace == "main" ? ["demojampublic.example.com", "*.example.com"] : ["*.example.com"], record.name)])
      error_message = "Proxied DNS record for demojampublic.example.com or its previews not found"
    }
  }
  name = {
    endswith = "example.com"
  }
  proxied = true
  zone_id = "0123456789abcdef0123456789abcdef01"
}

resource "cloudflare_workers_script" "this" {
  account_id = "0123456789abcdef0123456789abcdef00"
  assets = {
    config = {
      not_found_handling = "single-page-application"
      run_worker_first   = ["/api/*"]
    }
    directory = "../../../site"
  }
  compatibility_date = "2026-08-28"
  content            = "export default {\n    async fetch() {\n        return new Response('API placeholder')\n    },\n}\n"
  main_module        = "worker.js"
  script_name        = "demojampublic-${terraform.workspace}"
}

resource "cloudflare_workers_script_subdomain" "this" {
  account_id       = "0123456789abcdef0123456789abcdef00"
  enabled          = false
  previews_enabled = false
  script_name      = cloudflare_workers_script.this.script_name
}

resource "cloudflare_workers_route" "this" {
  pattern = terraform.workspace == "main" ? "demojampublic.example.com/*" : "demojampublic-${terraform.workspace}.example.com/*"
  script  = cloudflare_workers_script.this.script_name
  zone_id = "0123456789abcdef0123456789abcdef01"
}
