# AUTOGENERATED by helicopyter

terraform {
  required_providers {
    docker = {
      source = "kreuzwerker/docker"
      version = "3.4.0"
    }
  }
}

provider "docker" {}

resource "docker_image" "nginxImage" {
  name = "nginx:latest"
  keep_locally = false
}

resource "docker_container" "nginxContainer" {
  name = "tutorial"
  image = docker_image.nginxImage.name
  ports {
    internal = 80
    external = 8000
  }
}
