# AUTOGENERATED by helicopyter

terraform {
  required_providers {
    docker = {
      version = "3.4.0"
      source = "kreuzwerker/docker"
    }
  }
}

provider "docker" {
}

resource "docker_image" "nginxImage" {
  keep_locally = false
  name = "nginx:latest"
}

resource "docker_container" "nginxContainer" {
  image = "${docker_image.nginxImage.name}"
  name = "tutorial"
  ports {
    external = 8000
    internal = 80
  }
}
