# AUTOGENERATED by helicopyter

terraform {
  required_providers {
    github = {
      version = "6.2.2"
      source  = "integrations/github"
    }
  }
}

provider "github" {
}

resource "github_repository" "airdjang" {
  allow_auto_merge            = true
  allow_merge_commit          = false
  allow_rebase_merge          = true
  allow_squash_merge          = true
  allow_update_branch         = true
  delete_branch_on_merge      = true
  description                 = "Airflow + Django"
  has_downloads               = false
  has_issues                  = true
  has_projects                = false
  has_wiki                    = false
  merge_commit_message        = "PR_BODY"
  merge_commit_title          = "PR_TITLE"
  name                        = "airdjang"
  squash_merge_commit_message = "PR_BODY"
  squash_merge_commit_title   = "PR_TITLE"
  topics = [
    "airflow",
    "django",
    "python"
  ]
}

resource "github_repository" "allowedflare" {
  allow_auto_merge            = true
  allow_merge_commit          = false
  allow_rebase_merge          = true
  allow_squash_merge          = true
  allow_update_branch         = true
  delete_branch_on_merge      = true
  description                 = "Intranet connectivity for Django and more"
  has_downloads               = false
  has_issues                  = true
  has_projects                = false
  has_wiki                    = false
  merge_commit_message        = "PR_BODY"
  merge_commit_title          = "PR_TITLE"
  name                        = "allowedflare"
  squash_merge_commit_message = "PR_BODY"
  squash_merge_commit_title   = "PR_TITLE"
  topics = [
    "django",
    "python"
  ]
}

resource "github_repository" "helicopyter" {
  allow_auto_merge            = true
  allow_merge_commit          = false
  allow_rebase_merge          = true
  allow_squash_merge          = true
  allow_update_branch         = true
  delete_branch_on_merge      = true
  description                 = "Python-defined infrastructure"
  has_downloads               = false
  has_issues                  = true
  has_projects                = false
  has_wiki                    = false
  merge_commit_message        = "PR_BODY"
  merge_commit_title          = "PR_TITLE"
  name                        = "helicopyter"
  squash_merge_commit_message = "PR_BODY"
  squash_merge_commit_title   = "PR_TITLE"
  topics = [
    "ansible",
    "cdktf",
    "python",
    "terraform"
  ]
}
