line-length = 100
target-version = 'py312'

[format]
quote-style = 'single'
skip-magic-trailing-comma = true

[lint]
fixable = ['ALL']
ignore = [
    'ANN401', # `**kwargs: Any` is reasonable
    'COM812', # Insists on `join([],)` over `join([])`
    'D101',
    'D103',
    'D104',
    'D107',
    'EM101',  # Simple code is more important than simple tracebacks
    'EM102',  # Simple code is more important than simple tracebacks
    'INP001',
    # Demystify magic values with good variable names, comments, or other context. Follow
    # Rule Of Three for when to abstract.
    'PLR2004',
    'Q000',   # ruff format will single quote
    'Q001',   # ruff format will single quote
    'Q003',   # ruff format will single quote
    # N806 tries to lowercase classes; currently ignored on a line-by-line basis
    'S607',   # Using $PATH is pretty necessary for nvmrc, pyenv, venv, tfenv
    'SLF001', # Private member access is probably a last resort
    'TD002',  # The git log records who wrote a TODO line
    'TD003',  # Don't require issue links
    'TD004',  # A colon takes up space without really improving readability
    'TRY002', # Forces premature specialization; the right time to subclass is when the exception starts being caught
    'TRY003', # Forces premature specialization; the right time to subclass is when the exception starts being caught
]
select = ['ALL']

[lint.flake8-pytest-style]
parametrize-values-row-type = 'tuple'
parametrize-values-type = 'tuple'

[lint.isort]
split-on-trailing-comma = false

[lint.per-file-ignores]
'test_*' = [
    'PT013',   # `import pytest` would be inconsistent with other imports
    'N802',    # Test functions can match class names
    'PLR2004', # Tests can have magic values
    'PLR6301', # Test classes can ignore self
    'S101',    # Tests can have assertions
]

[lint.pydocstyle]
convention = 'pep257'
