defaults:
    run:
        shell: bash --noprofile --norc -o errexit -o nounset -o pipefail -o xtrace {0}
env:
    ALLOWEDFLARE_EMAIL: person@emailprovider.example
    ALLOWEDFLARE_PRIVATE_DOMAIN: organization.example
    CLOUDFLARE_ACCOUNT_ID: 0123456789abcdef0123456789abcdef00
    CLOUDFLARE_ZONE_ID: 0123456789abcdef0123456789abcdef01
    INSH_TF: tofu
    PATH: .venv/bin:/home/runner/.local/bin:/home/runner/.local/share/mise/shims:/usr/bin:/bin
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            # Real hash is head_ref on pull_request, ref on push
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref || github.ref }}
            - uses: jdx/mise-action@v3
              with:
                  experimental: true
            - run: mise run set-environment
            - run: mise run pre-commit
            - run: mise tvalid demo
            - run: mise test
            - run: .venv/bin/just build_twine
    tabularize:
        runs-on: ubuntu-latest
        steps:
            # Real hash is head_ref on pull_request, ref on push
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref || github.ref }}
            - uses: jdx/mise-action@v3
              with:
                  experimental: true
            - run: mise run tabularize

on: # yamllint disable-line rule:truthy
    pull_request:
    push:
        branches:
            - main
    workflow_dispatch:
run-name: Checking on behalf of ${{ github.actor }}
