# AUTOGENERATED by helicopyter

locals {
  cona = "demo_hcl"
  envi = terraform.workspace
}

resource "null_resource" "this" {
  triggers = {
    cona = local.cona
    envi = local.envi
  }
}

variable "giha" {
  type = string
}
